[2025-02-05T00:28:02.410+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T00:28:02.421+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-05T00:00:00+00:00 [queued]>
[2025-02-05T00:28:02.428+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-05T00:00:00+00:00 [queued]>
[2025-02-05T00:28:02.429+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T00:28:02.437+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.agg_locations_risk_score_run> on 2025-02-05 00:00:00+00:00
[2025-02-05T00:28:02.442+0000] {standard_task_runner.py:63} INFO - Started process 1681 to run task
[2025-02-05T00:28:02.445+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.agg_locations_risk_score_run', 'manual__2025-02-05T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmpwgc6gyb2']
[2025-02-05T00:28:02.446+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask model_credit_fraud.agg_locations_risk_score_run
[2025-02-05T00:28:02.483+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-05T00:00:00+00:00 [running]> on host eb20c43aeeb4
[2025-02-05T00:28:02.546+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.agg_locations_risk_score_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T00:00:00+00:00'
[2025-02-05T00:28:02.548+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T00:28:04.403+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T00:28:04.404+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpnfp_0t3j from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T00:28:04.409+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-05T00:28:04.413+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T00:28:04.419+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T00:28:04.421+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-05T00:28:04.422+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'agg_locations_risk_score', '--project-dir', '/tmp/tmpnfp_0t3j', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmpnfp_0t3j
[2025-02-05T00:28:04.435+0000] {logging_mixin.py:188} INFO - 00:28:04  Running with dbt=1.6.1
[2025-02-05T00:28:04.531+0000] {logging_mixin.py:188} INFO - 00:28:04  Registered adapter: postgres=1.6.1
[2025-02-05T00:28:04.803+0000] {logging_mixin.py:188} INFO - 00:28:04  Found 3 models, 1 snapshot, 5 tests, 1 source, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T00:28:04.806+0000] {logging_mixin.py:188} INFO - 00:28:04
[2025-02-05T00:28:04.860+0000] {logging_mixin.py:188} INFO - 00:28:04  Concurrency: 1 threads (target='prod')
[2025-02-05T00:28:04.861+0000] {logging_mixin.py:188} INFO - 00:28:04
[2025-02-05T00:28:04.865+0000] {logging_mixin.py:188} INFO - 00:28:04  1 of 1 START sql table model dm_credit_operations.agg_locations_risk_score ..... [RUN]
[2025-02-05T00:28:08.557+0000] {logging_mixin.py:188} INFO - 00:28:08  1 of 1 OK created sql table model dm_credit_operations.agg_locations_risk_score  [SELECT 5 in 3.69s]
[2025-02-05T00:28:08.573+0000] {logging_mixin.py:188} INFO - 00:28:08
[2025-02-05T00:28:08.575+0000] {logging_mixin.py:188} INFO - 00:28:08  Finished running 1 table model in 0 hours 0 minutes and 3.77 seconds (3.77s).
[2025-02-05T00:28:08.584+0000] {logging_mixin.py:188} INFO - 00:28:08
[2025-02-05T00:28:08.586+0000] {logging_mixin.py:188} INFO - 00:28:08  Completed successfully
[2025-02-05T00:28:08.586+0000] {logging_mixin.py:188} INFO - 00:28:08
[2025-02-05T00:28:08.587+0000] {logging_mixin.py:188} INFO - 00:28:08  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T00:28:09.332+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T00:28:09.361+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-05T00:28:09.362+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.agg_locations_risk_score', extra=None)]
[2025-02-05T00:28:09.363+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T00:28:09.365+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T00:28:09.387+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-05T00:28:09.411+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T00:28:09.432+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.agg_locations_risk_score_run, run_id=manual__2025-02-05T00:00:00+00:00, execution_date=20250205T000000, start_date=20250205T002802, end_date=20250205T002809
[2025-02-05T00:28:09.477+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T00:28:09.496+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T00:28:09.498+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-02-05T14:40:38.457+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T14:40:38.479+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-05T00:00:00+00:00 [queued]>
[2025-02-05T14:40:38.491+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-05T00:00:00+00:00 [queued]>
[2025-02-05T14:40:38.491+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T14:40:38.505+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.agg_locations_risk_score_run> on 2025-02-05 00:00:00+00:00
[2025-02-05T14:40:38.512+0000] {standard_task_runner.py:63} INFO - Started process 501 to run task
[2025-02-05T14:40:38.516+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.agg_locations_risk_score_run', 'manual__2025-02-05T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmpsh92b723']
[2025-02-05T14:40:38.517+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask model_credit_fraud.agg_locations_risk_score_run
[2025-02-05T14:40:38.578+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-05T00:00:00+00:00 [running]> on host eb17fa5f9c23
[2025-02-05T14:40:38.686+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.agg_locations_risk_score_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T00:00:00+00:00'
[2025-02-05T14:40:38.690+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T14:40:41.734+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T14:40:41.736+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmp8teley7b from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T14:40:41.745+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-05T14:40:41.751+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T14:40:41.762+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T14:40:41.764+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-05T14:40:41.764+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'agg_locations_risk_score', '--project-dir', '/tmp/tmp8teley7b', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmp8teley7b
[2025-02-05T14:40:41.796+0000] {logging_mixin.py:188} INFO - 14:40:41  Running with dbt=1.6.1
[2025-02-05T14:40:41.921+0000] {logging_mixin.py:188} INFO - 14:40:41  Registered adapter: postgres=1.6.1
[2025-02-05T14:40:42.656+0000] {logging_mixin.py:188} INFO - 14:40:42  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T14:40:42.660+0000] {logging_mixin.py:188} INFO - 14:40:42
[2025-02-05T14:40:42.738+0000] {logging_mixin.py:188} INFO - 14:40:42  Concurrency: 1 threads (target='prod')
[2025-02-05T14:40:42.741+0000] {logging_mixin.py:188} INFO - 14:40:42
[2025-02-05T14:40:42.747+0000] {logging_mixin.py:188} INFO - 14:40:42  1 of 1 START sql table model dm_credit_operations.agg_locations_risk_score ..... [RUN]
[2025-02-05T14:40:42.825+0000] {logging_mixin.py:188} INFO - 14:40:42  1 of 1 ERROR creating sql table model dm_credit_operations.agg_locations_risk_score  [ERROR in 0.08s]
[2025-02-05T14:40:42.840+0000] {logging_mixin.py:188} INFO - 14:40:42
[2025-02-05T14:40:42.842+0000] {logging_mixin.py:188} INFO - 14:40:42  Finished running 1 table model in 0 hours 0 minutes and 0.18 seconds (0.18s).
[2025-02-05T14:40:42.853+0000] {logging_mixin.py:188} INFO - 14:40:42
[2025-02-05T14:40:42.854+0000] {logging_mixin.py:188} INFO - 14:40:42  Completed with 1 error and 0 warnings:
[2025-02-05T14:40:42.855+0000] {logging_mixin.py:188} INFO - 14:40:42
[2025-02-05T14:40:42.856+0000] {logging_mixin.py:188} INFO - 14:40:42  Database Error in model agg_locations_risk_score (models/marts/credit_fraud/agg_locations_risk_score.sql)
[2025-02-05T14:40:42.857+0000] {logging_mixin.py:188} INFO - 14:40:42    relation "dm_credit_operations.stg_credit_fraud" does not exist
[2025-02-05T14:40:42.858+0000] {logging_mixin.py:188} INFO - 14:40:42    LINE 16:  "***"."dm_credit_operations"."stg_credit_fraud"
[2025-02-05T14:40:42.859+0000] {logging_mixin.py:188} INFO - 14:40:42              ^
[2025-02-05T14:40:42.860+0000] {logging_mixin.py:188} INFO - 14:40:42    compiled Code at target/run/***/models/marts/credit_fraud/agg_locations_risk_score.sql
[2025-02-05T14:40:42.861+0000] {logging_mixin.py:188} INFO - 14:40:42
[2025-02-05T14:40:42.863+0000] {logging_mixin.py:188} INFO - 14:40:42  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-02-05T14:40:43.621+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T14:40:43.625+0000] {local.py:494} INFO - Inlets: []
[2025-02-05T14:40:43.626+0000] {local.py:495} INFO - Outlets: []
[2025-02-05T14:40:43.626+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T14:40:43.627+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T14:40:43.641+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-05T14:40:43.665+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T14:40:43.675+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/base.py", line 268, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 654, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 509, in run_command
    self.handle_exception(result)
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 237, in handle_exception_dbt_runner
    raise AirflowException(f"dbt invocation completed with errors: {error_message}")
airflow.exceptions.AirflowException: dbt invocation completed with errors: agg_locations_risk_score: Database Error in model agg_locations_risk_score (models/marts/credit_fraud/agg_locations_risk_score.sql)
  relation "dm_credit_operations.stg_credit_fraud" does not exist
  LINE 16:  "***"."dm_credit_operations"."stg_credit_fraud"
            ^
  compiled Code at target/run/***/models/marts/credit_fraud/agg_locations_risk_score.sql
[2025-02-05T14:40:43.679+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.agg_locations_risk_score_run, run_id=manual__2025-02-05T00:00:00+00:00, execution_date=20250205T000000, start_date=20250205T144038, end_date=20250205T144043
[2025-02-05T14:40:43.690+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task model_credit_fraud.agg_locations_risk_score_run (dbt invocation completed with errors: agg_locations_risk_score: Database Error in model agg_locations_risk_score (models/marts/credit_fraud/agg_locations_risk_score.sql)
  relation "dm_credit_operations.stg_credit_fraud" does not exist
  LINE 16:  "***"."dm_credit_operations"."stg_credit_fraud"
            ^
  compiled Code at target/run/***/models/marts/credit_fraud/agg_locations_risk_score.sql; 501)
[2025-02-05T14:40:43.737+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-05T14:40:43.754+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T14:40:43.757+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
