[2025-02-05T01:33:34.295+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T01:33:34.309+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ingestion_daily-credit_fraud.bulk_file_load manual__2025-02-05T01:27:30.059909+00:00 [queued]>
[2025-02-05T01:33:34.317+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ingestion_daily-credit_fraud.bulk_file_load manual__2025-02-05T01:27:30.059909+00:00 [queued]>
[2025-02-05T01:33:34.318+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-02-05T01:33:34.329+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): bulk_file_load> on 2025-02-05 01:27:30.059909+00:00
[2025-02-05T01:33:33.790+0000] {standard_task_runner.py:63} INFO - Started process 2464 to run task
[2025-02-05T01:33:33.794+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ingestion_daily-credit_fraud', 'bulk_file_load', 'manual__2025-02-05T01:27:30.059909+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dag_ingestion_daily-fraud_credit.py', '--cfg-path', '/tmp/tmpb30mmqvq']
[2025-02-05T01:33:33.795+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask bulk_file_load
[2025-02-05T01:33:33.836+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ingestion_daily-credit_fraud.bulk_file_load manual__2025-02-05T01:27:30.059909+00:00 [running]> on host eb20c43aeeb4
[2025-02-05T01:33:33.907+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ingestion_daily-credit_fraud' AIRFLOW_CTX_TASK_ID='bulk_file_load' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T01:27:30.059909+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T01:27:30.059909+00:00'
[2025-02-05T01:33:33.910+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T01:33:33.922+0000] {sql.py:276} INFO - Executing: 
            COPY dm_credit_operations_stage.raw_credit_fraud FROM '/data/raw_fraud_credit.csv' DELIMITER ',' CSV HEADER;
        
[2025-02-05T01:33:33.931+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T01:33:33.976+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T01:33:33.980+0000] {sql.py:450} INFO - Running statement: 
            COPY dm_credit_operations_stage.raw_credit_fraud FROM '/data/raw_fraud_credit.csv' DELIMITER ',' CSV HEADER;
        , parameters: None
[2025-02-05T01:34:13.530+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T01:34:13.531+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DiskFull: could not extend file "base/16384/16514.2": wrote only 4096 of 8192 bytes at block 364574
HINT:  Check free disk space.
CONTEXT:  COPY raw_credit_fraud, line 5658595

[2025-02-05T01:34:13.546+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_ingestion_daily-credit_fraud, task_id=bulk_file_load, run_id=manual__2025-02-05T01:27:30.059909+00:00, execution_date=20250205T012730, start_date=20250205T013334, end_date=20250205T013413
[2025-02-05T01:34:13.561+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 46 for task bulk_file_load (could not extend file "base/16384/16514.2": wrote only 4096 of 8192 bytes at block 364574
HINT:  Check free disk space.
CONTEXT:  COPY raw_credit_fraud, line 5658595
; 2464)
[2025-02-05T01:34:13.599+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-05T01:34:13.614+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T01:34:13.617+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
