[2025-02-05T00:24:46.292+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T00:24:46.301+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ingestion_daily-credit_fraud.create_table manual__2025-02-05T00:24:43.081166+00:00 [queued]>
[2025-02-05T00:24:46.308+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ingestion_daily-credit_fraud.create_table manual__2025-02-05T00:24:43.081166+00:00 [queued]>
[2025-02-05T00:24:46.308+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-02-05T00:24:46.317+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2025-02-05 00:24:43.081166+00:00
[2025-02-05T00:24:46.322+0000] {standard_task_runner.py:63} INFO - Started process 1566 to run task
[2025-02-05T00:24:46.325+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ingestion_daily-credit_fraud', 'create_table', 'manual__2025-02-05T00:24:43.081166+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag_ingestion_daily-fraud_credit.py', '--cfg-path', '/tmp/tmpxfdud5y6']
[2025-02-05T00:24:46.326+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask create_table
[2025-02-05T00:24:46.364+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ingestion_daily-credit_fraud.create_table manual__2025-02-05T00:24:43.081166+00:00 [running]> on host eb20c43aeeb4
[2025-02-05T00:24:46.428+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ingestion_daily-credit_fraud' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T00:24:43.081166+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T00:24:43.081166+00:00'
[2025-02-05T00:24:46.429+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T00:24:46.439+0000] {sql.py:276} INFO - Executing: 
            DROP TABLE IF EXISTS dm_credit_operations_stage.raw_credit_fraud;
            CREATE TABLE dm_credit_operations_stage.raw_credit_fraud (
               timestamp VARCHAR(50) NULL,
               sending_address VARCHAR(50) NULL,
               receiving_address VARCHAR(50) NULL,
               amount VARCHAR(50) NULL,
               transaction_type VARCHAR(50) NULL,
               location_region VARCHAR(50) NULL,
               ip_prefix VARCHAR(50) NULL,
               login_frequency VARCHAR(50) NULL,
               session_duration VARCHAR(50) NULL,
               purchase_pattern VARCHAR(50) NULL,
               age_group VARCHAR(50) NULL,
               risk_score VARCHAR(50) NULL,
               anomaly VARCHAR(50) NULL
          );
        
[2025-02-05T00:24:46.446+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T00:24:46.481+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T00:24:46.485+0000] {sql.py:450} INFO - Running statement: 
            DROP TABLE IF EXISTS dm_credit_operations_stage.raw_credit_fraud;
            CREATE TABLE dm_credit_operations_stage.raw_credit_fraud (
               timestamp VARCHAR(50) NULL,
               sending_address VARCHAR(50) NULL,
               receiving_address VARCHAR(50) NULL,
               amount VARCHAR(50) NULL,
               transaction_type VARCHAR(50) NULL,
               location_region VARCHAR(50) NULL,
               ip_prefix VARCHAR(50) NULL,
               login_frequency VARCHAR(50) NULL,
               session_duration VARCHAR(50) NULL,
               purchase_pattern VARCHAR(50) NULL,
               age_group VARCHAR(50) NULL,
               risk_score VARCHAR(50) NULL,
               anomaly VARCHAR(50) NULL
          );
        , parameters: None
[2025-02-05T00:24:46.487+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T00:24:46.487+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DependentObjectsStillExist: cannot drop table dm_credit_operations_stage.raw_credit_fraud because other objects depend on it
DETAIL:  view dm_credit_operations.stg_credit_fraud depends on table dm_credit_operations_stage.raw_credit_fraud
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[2025-02-05T00:24:46.494+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_ingestion_daily-credit_fraud, task_id=create_table, run_id=manual__2025-02-05T00:24:43.081166+00:00, execution_date=20250205T002443, start_date=20250205T002446, end_date=20250205T002446
[2025-02-05T00:24:46.503+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task create_table (cannot drop table dm_credit_operations_stage.raw_credit_fraud because other objects depend on it
DETAIL:  view dm_credit_operations.stg_credit_fraud depends on table dm_credit_operations_stage.raw_credit_fraud
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
; 1566)
[2025-02-05T00:24:46.540+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-05T00:24:46.556+0000] {dagrun.py:941} ERROR - Failed to get task for ti <TaskInstance: dag_ingestion_daily-credit_fraud.trigger_processing_dag manual__2025-02-05T00:24:43.081166+00:00 [None]>. Marking it as removed.
[2025-02-05T00:24:46.562+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T00:24:46.564+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
